services:
  frontend:
    build: frontend
    ports:
      - "4200:80"
    networks:
      - back-tier
  
  backend:
    build: backend
    ports:
      - "8080:8080"
    networks:
      - back-tier

networks:
  back-tier: {}