services:
  frontend:
    build: frontend
    ports:
      - "4200:80"
    networks:
      - common-network
  
  backend:
    build: backend
    ports:
      - "8080:8080"
    networks:
      - common-network

networks:
  common-network: {}