name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Validate with Maven
        working-directory: ./backend
        run: mvn validate
      - name: Compile with Maven
        working-directory: ./backend
        run: mvn compile
      - name: Test with Maven
        working-directory: ./backend
        run: mvn test
              